// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleObject.proto

public final class SampleObjectProto {
  private SampleObjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SampleObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SampleObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    boolean hasProp1();
    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    String getProp1();
    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    com.google.protobuf.ByteString
        getProp1Bytes();

    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    boolean hasProp2();
    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    String getProp2();
    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    com.google.protobuf.ByteString
        getProp2Bytes();

    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    boolean hasProp3();
    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    String getProp3();
    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    com.google.protobuf.ByteString
        getProp3Bytes();

    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    boolean hasProp4();
    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    String getProp4();
    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    com.google.protobuf.ByteString
        getProp4Bytes();

    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    java.util.List<SampleObject>
        getChildrenList();
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    SampleObject getChildren(int index);
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    java.util.List<? extends SampleObjectOrBuilder>
        getChildrenOrBuilderList();
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    SampleObjectOrBuilder getChildrenOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code SampleObject}
   */
  public static final class SampleObject extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SampleObject)
      SampleObjectOrBuilder {
    // Use SampleObject.newBuilder() to construct.
    private SampleObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SampleObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SampleObject defaultInstance;
    public static SampleObject getDefaultInstance() {
      return defaultInstance;
    }

    public SampleObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SampleObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              prop1_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              prop2_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              prop3_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              prop4_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                children_ = new java.util.ArrayList<SampleObject>();
                mutable_bitField0_ |= 0x00000010;
              }
              children_.add(input.readMessage(SampleObject.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SampleObjectProto.internal_static_SampleObject_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SampleObjectProto.internal_static_SampleObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SampleObject.class, Builder.class);
    }

    public static com.google.protobuf.Parser<SampleObject> PARSER =
        new com.google.protobuf.AbstractParser<SampleObject>() {
      public SampleObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleObject(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SampleObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PROP1_FIELD_NUMBER = 1;
    private Object prop1_;
    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    public boolean hasProp1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    public String getProp1() {
      Object ref = prop1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prop1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prop1 = 1 [default = "property1"];</code>
     */
    public com.google.protobuf.ByteString
        getProp1Bytes() {
      Object ref = prop1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        prop1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROP2_FIELD_NUMBER = 2;
    private Object prop2_;
    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    public boolean hasProp2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    public String getProp2() {
      Object ref = prop2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prop2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prop2 = 2 [default = "property2"];</code>
     */
    public com.google.protobuf.ByteString
        getProp2Bytes() {
      Object ref = prop2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        prop2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROP3_FIELD_NUMBER = 3;
    private Object prop3_;
    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    public boolean hasProp3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    public String getProp3() {
      Object ref = prop3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prop3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prop3 = 3 [default = "property3"];</code>
     */
    public com.google.protobuf.ByteString
        getProp3Bytes() {
      Object ref = prop3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        prop3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROP4_FIELD_NUMBER = 4;
    private Object prop4_;
    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    public boolean hasProp4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    public String getProp4() {
      Object ref = prop4_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prop4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prop4 = 4 [default = "property4"];</code>
     */
    public com.google.protobuf.ByteString
        getProp4Bytes() {
      Object ref = prop4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        prop4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDREN_FIELD_NUMBER = 5;
    private java.util.List<SampleObject> children_;
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    public java.util.List<SampleObject> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    public java.util.List<? extends SampleObjectOrBuilder>
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    public SampleObject getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .SampleObject children = 5;</code>
     */
    public SampleObjectOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    private void initFields() {
      prop1_ = "property1";
      prop2_ = "property2";
      prop3_ = "property3";
      prop4_ = "property4";
      children_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProp1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProp2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProp3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProp4()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getChildrenCount(); i++) {
        if (!getChildren(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getProp1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getProp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getProp3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getProp4Bytes());
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(5, children_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProp1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getProp2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProp3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getProp4Bytes());
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, children_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SampleObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SampleObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SampleObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SampleObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SampleObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SampleObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SampleObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SampleObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SampleObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SampleObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SampleObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SampleObject)
        SampleObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SampleObjectProto.internal_static_SampleObject_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SampleObjectProto.internal_static_SampleObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SampleObject.class, Builder.class);
      }

      // Construct using SampleObjectProto.SampleObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        prop1_ = "property1";
        bitField0_ = (bitField0_ & ~0x00000001);
        prop2_ = "property2";
        bitField0_ = (bitField0_ & ~0x00000002);
        prop3_ = "property3";
        bitField0_ = (bitField0_ & ~0x00000004);
        prop4_ = "property4";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SampleObjectProto.internal_static_SampleObject_descriptor;
      }

      public SampleObject getDefaultInstanceForType() {
        return SampleObject.getDefaultInstance();
      }

      public SampleObject build() {
        SampleObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SampleObject buildPartial() {
        SampleObject result = new SampleObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.prop1_ = prop1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.prop2_ = prop2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.prop3_ = prop3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prop4_ = prop4_;
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SampleObject) {
          return mergeFrom((SampleObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SampleObject other) {
        if (other == SampleObject.getDefaultInstance()) return this;
        if (other.hasProp1()) {
          bitField0_ |= 0x00000001;
          prop1_ = other.prop1_;
          onChanged();
        }
        if (other.hasProp2()) {
          bitField0_ |= 0x00000002;
          prop2_ = other.prop2_;
          onChanged();
        }
        if (other.hasProp3()) {
          bitField0_ |= 0x00000004;
          prop3_ = other.prop3_;
          onChanged();
        }
        if (other.hasProp4()) {
          bitField0_ |= 0x00000008;
          prop4_ = other.prop4_;
          onChanged();
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000010);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProp1()) {
          
          return false;
        }
        if (!hasProp2()) {
          
          return false;
        }
        if (!hasProp3()) {
          
          return false;
        }
        if (!hasProp4()) {
          
          return false;
        }
        for (int i = 0; i < getChildrenCount(); i++) {
          if (!getChildren(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SampleObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SampleObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object prop1_ = "property1";
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public boolean hasProp1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public String getProp1() {
        Object ref = prop1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prop1_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public com.google.protobuf.ByteString
          getProp1Bytes() {
        Object ref = prop1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          prop1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public Builder setProp1(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        prop1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public Builder clearProp1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        prop1_ = getDefaultInstance().getProp1();
        onChanged();
        return this;
      }
      /**
       * <code>required string prop1 = 1 [default = "property1"];</code>
       */
      public Builder setProp1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        prop1_ = value;
        onChanged();
        return this;
      }

      private Object prop2_ = "property2";
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public boolean hasProp2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public String getProp2() {
        Object ref = prop2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prop2_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public com.google.protobuf.ByteString
          getProp2Bytes() {
        Object ref = prop2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          prop2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public Builder setProp2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        prop2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public Builder clearProp2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        prop2_ = getDefaultInstance().getProp2();
        onChanged();
        return this;
      }
      /**
       * <code>required string prop2 = 2 [default = "property2"];</code>
       */
      public Builder setProp2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        prop2_ = value;
        onChanged();
        return this;
      }

      private Object prop3_ = "property3";
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public boolean hasProp3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public String getProp3() {
        Object ref = prop3_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prop3_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public com.google.protobuf.ByteString
          getProp3Bytes() {
        Object ref = prop3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          prop3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public Builder setProp3(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        prop3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public Builder clearProp3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prop3_ = getDefaultInstance().getProp3();
        onChanged();
        return this;
      }
      /**
       * <code>required string prop3 = 3 [default = "property3"];</code>
       */
      public Builder setProp3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        prop3_ = value;
        onChanged();
        return this;
      }

      private Object prop4_ = "property4";
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public boolean hasProp4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public String getProp4() {
        Object ref = prop4_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prop4_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public com.google.protobuf.ByteString
          getProp4Bytes() {
        Object ref = prop4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          prop4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public Builder setProp4(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prop4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public Builder clearProp4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prop4_ = getDefaultInstance().getProp4();
        onChanged();
        return this;
      }
      /**
       * <code>required string prop4 = 4 [default = "property4"];</code>
       */
      public Builder setProp4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prop4_ = value;
        onChanged();
        return this;
      }

      private java.util.List<SampleObject> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = new java.util.ArrayList<SampleObject>(children_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          SampleObject, Builder, SampleObjectOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public java.util.List<SampleObject> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public SampleObject getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder setChildren(
          int index, SampleObject value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder setChildren(
          int index, Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildren(SampleObject value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildren(
          int index, SampleObject value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildren(
          Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildren(
          int index, Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addAllChildren(
          Iterable<? extends SampleObject> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public SampleObjectOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public java.util.List<? extends SampleObjectOrBuilder>
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            SampleObject.getDefaultInstance());
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, SampleObject.getDefaultInstance());
      }
      /**
       * <code>repeated .SampleObject children = 5;</code>
       */
      public java.util.List<Builder>
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          SampleObject, Builder, SampleObjectOrBuilder>
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              SampleObject, Builder, SampleObjectOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SampleObject)
    }

    static {
      defaultInstance = new SampleObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SampleObject)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SampleObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SampleObject.proto\"\227\001\n\014SampleObject\022\030\n" +
      "\005prop1\030\001 \002(\t:\tproperty1\022\030\n\005prop2\030\002 \002(\t:\t" +
      "property2\022\030\n\005prop3\030\003 \002(\t:\tproperty3\022\030\n\005p" +
      "rop4\030\004 \002(\t:\tproperty4\022\037\n\010children\030\005 \003(\0132" +
      "\r.SampleObjectB\023B\021SampleObjectProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SampleObject_descriptor,
        new String[] { "Prop1", "Prop2", "Prop3", "Prop4", "Children", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
